### ISSUE TITLE
Little question, run this script under ubuntu ?

### ISSUE THREAD

**Issue by BogusCurry** [GuduleLapointe/opensim-debian#4]
Hi there ;D
Nice project, but I have too question, can ..
- this script run under ubuntu ?
- can I change the opsim version from 0.8x too 0.9x ?
- and is this for grid or standalone ?

But I will test this script, I think is very nice what you do make, thank you for that ;D

Have a nice Day ;D

**Comment by magicoli** [comment]
Le 11/12/2016 à 16:57, Bogus curry a écrit :
>
> Hi there ;D
> Nice project, but I have too question, can ..
>
>   * this script run under ubuntu ?
>
Yes, Debian / Ubuntu, same fight: I use Debian on public servers and 
Ubuntu at home.
>
>   * can I change the opsim version from 0.8x too 0.9x ?
>
Yes, I use both version and they work fine. I had to check carefully the 
settings file when switching, though.
>
>   * and is this for grid or standalone ?
>
It is intended for grids. but it works for standalone. However, with 
standalone, there is no real added value using it, compared to official 
dist or a dedicated one like Diva's. The goal here is to have a better 
organisation between shared, cache, specific files, which makes mostly 
sense when there are several instances running on the same machine.

> But I will test this script, I think is very nice what you do make, 
> thank you for that ;D
>
Please share your feeling and remarks, so I can perfect the project!

> Have a nice Day ;D
>
Thank you for your interest, have a nice day too
