### ISSUE TITLE
Question: Is the projekt closed ?

### ISSUE THREAD

**Issue by BogusCurry** [GuduleLapointe/opensim-debian#5]
Hi there ;D

Is the projekt closed ?

Have a nice day ;D

Bogus

**Comment by GuduleLapointe** [comment]
Hello. No, it still open, although I didn't work  a lot on it lately.

**Comment by BogusCurry** [comment]
Hello ;D
The url to the gitlab is broken ;(

**Comment by GuduleLapointe** [comment]
Sorry, yes, gitlab repo is offline, the only valid repo is now on github
